import UsePWA from '@/components/UsePWA';
import Header from '@/components/layout/Header';
import Main from '@/components/layout/Main';
import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';

import './globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <div id="app" className="mx-auto max-w-3xl">
          <Header />
          <Main>{children}</Main>
        </div>
        <div id="catalog-portal"></div>
      </body>
      <UsePWA />
    </html>
  );
}
